### ISSUE TITLE
Docker container does not support OpenCage

### ISSUE THREAD

**Issue by frootmig** [owntracks/docker-recorder#19]
After having problems with Google Geo API limits I wanted to switch to OpenCage. As far as I can see, the container lacks support for lua-opencage-geocoder. I tried to modify the Dockerfile to get lua-opencage-geocoder installed. I modified the RUN as followed:

```
RUN apt-get update && \
        apt-get install -y gnupg && \
        apt-key add /tmp/owntracks.gpg.key && \
        apt-get update && \
        apt-get install -y software-properties-common net-tools && \
        apt-add-repository 'deb http://repo.owntracks.org/debian stretch main' && \
        apt-get update && \
        apt-get install -y \
                libmosquitto1 \
                libsodium18 \
                libcurl3 \
                lua5.2 \
                liblua5.2-0 \
                liblua5.2-dev \
                mosquitto \
                mosquitto-clients \
                supervisor \
                ot-recorder \
                curl \
                luarocks \
                && \
        luarocks install lua-opencage-geocoder && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/*
```

I also added `COPY opencage.lua /usr/local/share/opencage.lua` to have the script available inside of the container. The container build shows a warning:

```
Installing https://luarocks.org/lua-cjson-2.1.0.6-1.src.rock
lua_cjson.c: In function 'json_append_data':
lua_cjson.c:743:19: warning: implicit declaration of function 'lua_objlen' [-Wimplicit-function-declaration]
             len = lua_objlen(l, -1);
                   ^~~~~~~~~~
gcc -O2 -fPIC -I/usr/include/lua5.2 -c lua_cjson.c -o lua_cjson.o
gcc -O2 -fPIC -I/usr/include/lua5.2 -c strbuf.c -o strbuf.o
gcc -O2 -fPIC -I/usr/include/lua5.2 -c fpconv.c -o fpconv.o
gcc -shared -o cjson.so -L/usr/local/lib lua_cjson.o strbuf.o fpconv.o
lua-cjson 2.1.0.6-1 is now installed in /usr/local (license: MIT)

lua-opencage-geocoder 0.1-0 is now installed in /usr/local (license: MIT <http://opensource.org/licenses/MIT>)
```
But with these modifications Recorder fails:

```
mosquitto-owntracks    | ot-recorder[37]: initializing Lua hooks from `/usr/local/share/opencage.lua'
mosquitto-owntracks    | ot-recorder[37]: Cannot load Lua from /usr/local/share/opencage.lua: error loading module 'cjson' from file '/usr/local/lib/lua/5.2/cjson.so':
mosquitto-owntracks    |        /usr/local/lib/lua/5.2/cjson.so: undefined symbol: lua_objlen
mosquitto-owntracks    | ot-recorder[37]: Cannot invoke Lua function otr_exit: (null)
mosquitto-owntracks    | ot-recorder[37]: unloading Lua: failed to load script
mosquitto-owntracks    | ot-recorder[37]: Stopping because loading of Lua script /usr/local/share/opencage.lua failed
```

Any advice how to fix this? I am a bit confused which package requires which version of lua. Is lua 5.1 or 5.2 required? Both choices seem to lead to errors. As of I am not sure which version to choose it might be just the wrong lua version.

Another option might be, that cjson may not be used in the current version, as of it has fixes for a incompatibility between lua 5.1 and 5.2.

**Comment by juzam** [comment]
There is a Stretch Debian package for `lua-cjson` which we can probably use instead of compiling from sources. (https://packages.debian.org/stretch/lua-cjson) I can't test this atm, so could you please check if installing this package solves the issue? Thanks

**Comment by frootmig** [comment]
There is a package. I can not yet confirm, that it really works, because I have an issue with opencage.lua script I need to figure out first.

**Comment by frootmig** [comment]
I was able to isolate the problem with the lua script. os.getenv("OPENCAGE_APIKEY") returns nil. In fact, no variable listed in ot-recorder.default and recognized in Recorder is passed to the script. Is this expected to work?

**Comment by jpmens** [comment]
What are you doing with Lua?

The Recorder by default (if configured and built appropriately) uses OpenCage via `geo.c` which is triggered by a prefix of `opencage:` in the Geo API key.

The Lua file you mention is just there for demo purposes.

**Comment by jpmens** [comment]
Ok, yes, I think we need to change that text. 

Please look for `--geokey` in the top-level README of the Recorder.

**Comment by frootmig** [comment]
It seems to work that way, at least, I can no longer see error messages in the log.

Would lua support for the dockerized recorder be usefull? If yes, I can provide a pull request to add this support. If no, I think I can just revert my changes.

I still need to figure out why it's not possible to use traefik as reverse proxy and how configure Owntracks on iOS to not eat all of my batterie. But that's another question.

**Comment by jpmens** [comment]
Lua is useful because Recorder can use Lua scripts on demand.

**Comment by jpmens** [comment]
OwnTracks on iOS doesn't typically eat battery. I assume you have move mode configured. In either case open an issue on our iOS tracker please.

**Comment by jpmens** [comment]
I am closing this, because the **new** Docker image supports OpenCAGE, but be warned: we no longer come bundled with an MQTT broker. The README in this repository explains how to run with docker-compose.

**Comment by frootmig** [comment]
Thank you very much @jpmens. I migrated everything to the new container and it seems to work like a charm now.
