### ISSUE TITLE
Heads up: repository now renamed to docker-recorder

### ISSUE THREAD

**Issue by jpmens** [owntracks/docker-recorder#21]
... as discussed in #13

**Comment by jpmens** [comment]
@deisi and/or @juzam I think I now need a bit of help on how to replace the image on docker hub. I've created a new `owntracks/recorder` and the site looks like this:

![jmbp-4946](https://user-images.githubusercontent.com/60706/50895450-6cd88800-1406-11e9-8c7a-4b9af1bce77c.png)

How do I continue?

**Comment by juzam** [comment]
@jpmens I think you shoul recreate the Docker repository, in order to tie it to the github repo. you should see something like this: 

![image](https://user-images.githubusercontent.com/1434180/50896028-19ffd000-1408-11e9-8655-c6e53790befc.png)

You probably need to relink your github account (since the last time I've used it it needed to be relinked as they changed the method)

After choosing github org `onwntracks` you should select `docker-recorder`

after that you can create the repo, and under builds there are ways to auto trigger the build on push to the github record or manually.

**Comment by jpmens** [comment]
That doesn't seem to work any more, at least not with the `owntracks` organization; it links to my (`jpmens`) github account only and can thus not find the OwnTracks repositories.

Not a problem for now, as I can `docker push owntracks/recorder` from the CLI which, I assume, amounts to the same.

Any suggestion as to tagging?

**Comment by juzam** [comment]
> That doesn't seem to work any more, at least not with the `owntracks` organization; it links to my (`jpmens`) github account only and can thus not find the OwnTracks repositories.

ah! I should have probably noticed since I'm in the owntracks github organization  that's an unfortunate change.

> Not a problem for now, as I can `docker push owntracks/recorder` from the CLI which, I assume, amounts to the same.

Yes I think this should work, for now. 

> Any suggestion as to tagging?

I would just go with `latest` and `1.0` for a start.

**Comment by deisi** [comment]
`latest` and `1.0` sound good

**Comment by jpmens** [comment]
A disadvantage of `1.0` is that we can't tell from "outside" which version of Recorder is actually in there (I'm thinking of "support queries").

Would it not be clever to match the tag to the Recorder version? Or is that just not done?

**Comment by juzam** [comment]
As it is the recorder version that gets installed in the docker image is defined by https://github.com/owntracks/docker-recorder/blob/92e48011f11ce6d4a7dd3a8c6852f691c675cef7/Dockerfile#L10

That is used later to download the relevant release from github and build from the sources.
So it could be sensible to use that tag (that has to be kept up to date with the Recorder version)

**Comment by deisi** [comment]
Also possible, however we should have an idea what happens if the docker container changes for what ever reason but not the recorder code base.

**Comment by jpmens** [comment]
Would `<RECORDER_VERSION>-<docker-container>` make sense?

```
0.8.0-1    current recorder, first docker image
0.8.0-2    current recoder, second docker image
0.8.1-1    next recorder version (maybe), first docker image for that version
```

**Comment by deisi** [comment]
:+1:

**Comment by jpmens** [comment]
Done.
