### ISSUE TITLE
CAFILE can't be opened

### ISSUE THREAD

**Issue by mattsches** [owntracks/docker-recorder#27]
recorder version: 0.8.3 (latest Docker image)
OS: Docker on Synology
MQTT broker: mosquitto 1.4.8 on external server/domain with Let's Encrypt certs

I'm running recorder on my Synology NAS using Docker. Everything works fine when I'm _not_ using TLS (ie. over port 1883), but when I configure it to use port 8883 and set an `OTR_CAFILE = le-all.pem` (using the contents of https://gist.github.com/jpmens/211dbe7904a0efd40e2e590066582ae5), it returns

```
ot-recorder[7]: cafile configured as `le-all.pem' can't be opened: errno=2
```

and the Docker container stops.

`le-all.pem` is in my `…/config` directory which is mounted as `/config`, double-checked the permissions, and also tried different file names or paths. Tried setting the option both as Docker env variable and in `recorder.conf`.

Looking through older issues (esp. relating to LE) I didn't find anything that helped. I've got the feeling that maybe it's just a misinterpretation of the docs on my behalf. Glad to provide any further info that helps resolve this :)

**Comment by jpmens** [comment]
@mattsches in #28 we just had similar issues. Could you please check with the step-by-step demonstration I gave there whether that helps you?

**Comment by mattsches** [comment]
It looks like you gave the right tip in https://github.com/owntracks/docker-recorder/issues/28#issuecomment-469831107 :)

I commented out `OTR_CERTFILE` and `OTR_KEYFILE` in my `recorder.conf` and set `OTR_CAFILE = /config/le-all.pem`, and now ot-recorder connects to my MQTT server via TLS.

Thanks a lot for your help, @jpmens

**Comment by mattsches** [comment]
Thank you for the commit, I think it's a good fix to avoid confusion.
