### ISSUE TITLE
Invalid function arguments provided with TLS connection

### ISSUE THREAD

**Issue by wasmitnetzen** [owntracks/docker-recorder#28]
(I have probably the same issue as #27, but to not confuse two debugging sessions, I'm opening another bug.)

I am trying to get recorder to run inside docker in a current version. I already have a self-compiled version 0.7.6 running on another server using the same broker, so I'm pretty sure it is not a settings issue.

To test this issue, I tried to run the docker container with a shell as an entrypoint with mounting the config folder:
`docker run -v /var/lib/recorder/config:/config --entrypoint /bin/sh --no-healthcheck -it owntracks/recorder`
with the `le-all.pem` from [here](https://gist.github.com/jpmens/211dbe7904a0efd40e2e590066582ae5) in `/var/lib/recorder/config`

This launches a shell, where I can provide any random (or working) credentials,
`export OTR_USER="username"`
`export OTR_PASS="password"`
`export OTR_CAFILE=/config/le-all.pem`
`ot-recorder --host mosquitto.example.org --port 8883 "owntracks/#"`

it always shows:
`ot-recorder[11]: version 0.8.3 starting with STORAGEDIR=/store`
`Cannot set TLS CA: Invalid function arguments provided. (check path names)`

So you can see that there isn't even a connection attempt made.

`ls /config` and `less /config/le-all.pem` both show the expected values.

**Comment by jpmens** [comment]
According to [the documentation](https://mosquitto.org/api/files/mosquitto-h.html#mosquitto_tls_set) either an out-of-memory situation is ocurring (which I think is out of the question), or input parameters are invalid. Possible reaons here that I'm aware of include incorrect file formats (e.g. not PEM certificates) or garbage files, etc. I assume you have checked the vailidity of the inputs, but I'd like you do do so explicitly please:

```
openssl x509 -in /config/le-all.pem -noout -dates -subject
```

for example. (You'll probably do this outside of the container.)

Could you please also confirm that 

```
OTR_CAPATH
OTR_CERTFILE
OTR_KEYFILE
```

are all not used in your configuration, i.e. are commented out with a `#`?

**Comment by jpmens** [comment]
If you're able to recompile, I would also appreciate the following test: on line 1668 of `recorder.c` it says:

```
rc = mosquitto_tls_set(mosq
```

Could you **insert** the following line and recompile?

```
ud->capath = ud->certfile = ud->keyfile = NULL;
rc = mosquitto_tls_set(mosq
```

I am explicitly setting those three values to NULL, overwriting whatever was in them to see if that solves the issue, and whether we have some garbage in those variables although I don't see where from ...

**Comment by jpmens** [comment]
I cannot reproduce it here. I've run your steps, including downloading `le-pem.all` as you did.

```
$ cat config/recorder.conf
OTR_CAFILE = "/config/le-all.pem"

$ wc -l config/le-all.pem
     179 config/le-all.pem

$ cat tls-run.sh
docker run -v /tmp/config:/config --entrypoint /bin/sh --no-healthcheck -it owntracks/recorder

$ ./tls-run.sh
/ #
/ # ot-recorder --host <internal> --port 8883 "owntracks/#"
ot-recorder[7]: version 0.8.3 starting with STORAGEDIR=/store
ot-recorder[7]: connecting to MQTT on <internal>:8883 as clientID ot-recorder-cd7370427986-7 with TLS
ot-recorder[7]: HTTP listener started on 127.0.0.1:8083
ot-recorder[7]: Using storage at /store with precision 7
ot-recorder[7]: Subscribing to owntracks/# (qos=2)
```

**Comment by wasmitnetzen** [comment]
Well, you already solved it. Of course it was a configuration issue...

There was a `recorder.conf`inside `/var/lib/recorder/config` which I thought I had checked, but it still defined a OTR_KEYFILE and OTR_CERTFILE. Once I removed those from the configuration, it worked.

Thank you!

**Comment by jpmens** [comment]
Thanks for reporting back; that's the kind of think that would have kept me up way past bed time. :-)
