### ISSUE TITLE
some recorder.conf variables ignored.

### ISSUE THREAD

**Issue by davidsmoot** [owntracks/docker-recorder#31]
Docker rookie so take that into account.
Started the ot-recorder docker with a local directory as the config directory.  I had to so that my OTR_CAFILE was accessible.  I had a previously working ot-recorder working on my Ubuntu box but the 19.04 upgrade broke it.  So I know I had a good working configuration that I just had to duplicate in the docker setup.
Edited the recorder.conf to assign values to OTR_CAFILE, OTR_HOST, OTR_USER, OTR_PASS, and OTR_PORT and started the docker container without the -d option to see output.  It ignored the user and port variables and tried to use the defaults but it honored the CAFILE and the HOST options.  Everything is quoted.
But everything works if I specify the same values from the command line with -e. 
I don't need this fixed, I have a working solution but I am willing to help troubleshoot / provide access to my system if there is a desire to investigate.  But also feel free to close as "won't fix", I have a perfectly working workaround.

**Comment by jpmens** [comment]
I'm not quite sure what the issue is ...

Are you saying that environment variables override the `recorder.conf` settings? I think that's intentional, and it should be [documented](https://github.com/owntracks/recorder/blob/master/README.md) that way.

**Comment by davidsmoot** [comment]
I'm saying that if I edit the recorder.conf file to have
OTR_PORT="1234"
OTR_USER="foo"
OTR_HOST="bar"
and I start the container without any command line switches, it will try to connect to "bar" but it will ignore the port and user tags and use the defaults.  
If I start the container with the command line overrides, "-e OTR_PORT=1234" exactly the same syntax (minus quotes) as the recorder.conf, the container will connect to the proper port with the proper credentials.  
Sorry for the poorly worded bug report.  I know the recorder.conf is being parsed, because if I change the host in the recorder.conf (and don't override it at the command line), the changes are reflected in the connection.  But either I am just blind to the correct syntax in recorder.conf or some of the options in recorder.conf are not correctly parsed.  The tag for OTR_CAFILE in recorder.conf is definitely being correctly parsed because it can connect.   The tags for OTR_PORT and OTR_USER in recorder.conf appear to be ignored and the only way I could get the system to work was to specify them in the command line. 
Hopefully this is clearer.  Again, I have a working solution but I just thought you might want to know.

**Comment by jpmens** [comment]
I cannot find a difference between the handling of `OTR_HOST` and `OTR_PORT` (as an example of options for which one works for you and the second doesn't)

As far as I can determine from the code, other than `OTR_PORT` eing an integer, --- ah, that's the problem?

Have you tried

```
OTR_PORT = 1234
```

without the quotes?

**Comment by jpmens** [comment]
Clarification: it's working as `-e OTR_PORT="1234"` for you on the command line, because a shell is stripping the quotes, however, within the configuration file we require the syntax imposed by the types in libconfig.

Using [our example file](https://github.com/owntracks/recorder/blob/master/etc/ot-recorder.default) should (famous last words) indicate the correct syntax.

**Comment by davidsmoot** [comment]
XXXX@proteus:~$ mkdir testcfg  
XXXX@proteus:~$ mkdir teststore 
  
XXXX@proteus:~$ sudo docker run -p 8084:8084 -v /home/XXXX/teststore/:/store -v /home/XXXX/testcfg/:/config owntracks/recorder    
ot-recorder[8]: version 0.8.3 starting with STORAGEDIR=/store  
ot-recorder[8]: connecting to MQTT on localhost:1883 as clientID ot-recorder-261d2a8286c3-8 without TLS  
Error: Address not available 
  
This causes recorder.conf to be created in the local directory /home/XXXX/testcfg/ on the docker host. 

Edit recorder.conf. 


XXXX@proteus:~$ more testcfg/recorder.conf   
#(@)ot-recorder.default  
#  
# Specify global configuration options for the OwnTracks Recorder  
# and its associated utilities to override compiled-in defaults.  
 
OTR_TOPICS = "owntracks/#"  
OTR_HTTPHOST = "0.0.0.0"  
OTR_CAPATH = "/config"  
OTR_HOST="foo"  
OTR_PORT="8883"  
OTR_USER="bar"  
 
# OTR_CAFILE = "ca.pem"  
 
# OTR_CERTFILE = "cert.pem"  
# OTR_KEYFILE = "key.pem" 
  
XXXX@proteus:~$ sudo docker run -p 8084:8084 -v /home/XXXX/teststore/:/store -v /home/XXXX/testcfg/:/config owntracks/recorder  
ot-recorder[7]: version 0.8.3 starting with STORAGEDIR=/store  
ot-recorder[7]: connecting to MQTT on foo:1883 as clientID ot-recorder-fc215f184805-7 without TLS 
 

Maybe I don't understand but after editing the default recorder.conf that was created on first run, I would expect the user printed out on the second run to be the "bar" I specified in recorder.conf.  But as you can see from the output, client ID is ot-recorder-fc215f184805-7  

That is my bug (or my misunderstanding).  When I edit the recorder.conf in a local directory, it will correctly parse out the expected value fo "OTR_HOST" from that file but will not correctly parse out "OTR_USER".  When I specify OTR_USER at the command line with the -e, it is honored and correctly applied.
David

**Comment by jpmens** [comment]
Formatting of code: on Github, place code/configs between two lines containing three backticks each (```) 

The MQTT clientId (`clientID ot-recorder-fc215f184805-7` in your last example) is not the username you specify with `OTR_HOST`. ClientID is the MQTT client specifyier which is given in the connection to the broker.

You can change that by setting `OTR_CLIENTID`, but please note clients MUST have unique identifiers (two clients connecting to one broker with the same ID will be kicked out)

**Comment by davidsmoot** [comment]
Bug withdrawn.
So the only "real" problem was that my recorder.conf file had the OTR_PORT in quotes.  That combined with my misconception about ClientID led me to file a report.  
So a very minor issue in reality, a quoted value for port in recorder.conf does not work.  Thanks for your help and patience again.
