### ISSUE TITLE
ot-recorder should not run as root

### ISSUE THREAD

**Issue by marcopaganini** [owntracks/docker-recorder#32]
We should avoid running binaries as root inside docker containers whenever possible. ot-recorder runs as root by default, but it's possible to run it as another user without changes to the Dockerfile. Maybe an update to the documentation to reflect the instructions above could be helpful for some people out there.

To run as another user, first create a user on the host just for `ot-recorder`. Resist the temptation of using the existing `nobody` user. Let's suppose we're using user `recorder` and group `recorder`, both with the same uid/gid (10000). The examples below work on a Debian system, but should be similar to most other distros:

```
export user=recorder
export uid=10000
sudo groupadd -g $uid $user
sudo useradd -c "$user" -d "/nonexistent" -g "$user" --uid $uid -s "/usr/sbin/nologin" $user
```

Now, create a directory to hold your static data. AFAICT, we can't use docker volumes (without altering the Dockerfile) as docker always mounts those as root:

```
mkdir /path/to/store/recorder/data
chown recorder:recorder /path/to/store/recorder/data
```

When running the container with `docker run`, replace the `-v docker_store:/store` option with `-v /path/to/store/recorder/data:/store` and add `-u 10000:10000`. Note that we need to use the UID/GID of the just user "recorder" on the host. We can't just use the string "recorder" here since this user is not available inside the docker container.

This works, but proper support for non-root users by default inside the Dockerfile would be a better solution.

**Comment by jpmens** [comment]
Thanks for your suggestion. Why do we need a dedicated user/group on the host system? I don't think this is required.

We'll gladly entertain a pull-request which implements this.

**Comment by marcopaganini** [comment]
The reason is that it appears volumes can only be mounted as root. Without
volumes, the only other solution is to map something in the host
filesystem. For that, you'd need a host user/group.

**Comment by jpmens** [comment]
It is clearly visible that I'm not a Docker specialist, but I cannot imagine requring a host user/group.

In fact [this page](https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b) suggests it's not required, at least that's how I understand it:

```
FROM <base image>
RUN groupadd -g 999 appuser && \
    useradd -r -u 999 -g appuser appuser
USER appuser
```

From here onwards, our Recorder would run as user _appuser_, and I think that sounds like what you are asking for.

Are you able to test this, to make sure permissions on the data volume don't need changing?

That same link, btw, explains it is possible to _voluntarily_ launch the container as non-root.

**Comment by marcopaganini** [comment]
Oh, I'm far from a docker specialist myself. :)

I don't believe your suggestion would work because it seems docker always mounts volumes as root.

See this example:

```bash
$ cat Dockerfile
FROM debian
RUN groupadd -g 999 appuser && \
    useradd -r -u 999 -g appuser appuser
USER appuser

$ docker build -t voltest:latest .
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM debian
 ---> 971452c94376
Step 2/3 : RUN groupadd -g 999 appuser &&     useradd -r -u 999 -g appuser appuser
 ---> Using cache
 ---> c0991713bdaf
Step 3/3 : USER appuser
 ---> Using cache
 ---> d325f2b5d689
Successfully built d325f2b5d689
Successfully tagged voltest:latest

$ docker volume create foobar
foobar

$ docker run -it --rm -v foobar:/foobar voltest
appuser@e1edf851f736:/$ ls -ltrd /foobar
drwxr-xr-x 2 root root 4096 Mar 12 04:03 /foobar

appuser@e1edf851f736:/$ id
uid=999(appuser) gid=999(appuser) groups=999(appuser)
```
As we can see, even when we specify a user, docker seems to always mount the volume as root (which is weird, but docker is weird.) The instructions I originally wrote work around this by mounting a directory on the host machine (which is not as nice as a clean volume), but require no modifications to Dockerfile.

If you're open to the idea of patches to the Dockerfile, we can create the appuser command above (with an ID in an env var, defaulting to 999) and upon execution chmod the mounted directory to that user, downgrade privileges and then run ot-recorder with that user.

Would that be an acceptable solution to you?
