### ISSUE TITLE
exec user process caused "exec format error"

### ISSUE THREAD

**Issue by MrMiracles** [owntracks/docker-recorder#36]
When trying to start the docker image I get this error:
`standard_init_linux.go:211: exec user process caused "exec format error".`

I search around on the internet, most people say it's a problem with the architecture. I tried to run this on mu Raspberry Pi 3+. that should work as far as I know?

**Comment by jpmens** [comment]
I should think it won't work as we build the containers for the x86_64 architecture.

We have Recorder packages for Raspbian in armhf architecture, so you could try those.

**Comment by MrMiracles** [comment]
Allright, i couldn't find that information. But I will have to create a container myself then. thanks!
