### ISSUE TITLE
How to add some views ?

### ISSUE THREAD

**Issue by surf33** [owntracks/docker-recorder#37]
I am using this docker (thanks for it!). I would like to use views. In the documentation : It says " htdocs/views/ this path is actually configurable with the --viewsdir option."

When using a docker, is it possible to have a volume for this purpose ? or Is it possible to change the configuration "--viewsdir" with an environnement variable (or the config file recorder.conf) ? 

Regards,

**Comment by jpmens** [comment]
Our `entrypoint.sh` takes arguments, so that ought to be possible, by adding what you need to the end of the `docker run` invocation.

**Comment by surf33** [comment]
I have tried to pass the argument. The execution command is _/entrypoint.sh --viewdir /volume1/docker/owntracks/views_  
the  web interface on http://127.0.0.1:8083  works but not the new viewsdir directory.

I have tried also with -_-viewdir "/volume1/docker/owntracks/views"_  same results

any ideas ?

**Comment by grheard** [comment]
Looks like the '--viewsdir /volume1/docker/owntracks/views' is the path outside of the docker volume. You need to provide a volume to the views dir that can be reached from inside the container.

**Comment by jpmens** [comment]
Your answer is correct, @grheard, on both accounts. :) Closing now.
