### ISSUE TITLE
Unable to run image

### ISSUE THREAD

**Issue by olegmeister** [owntracks/docker-recorder#43]
Hi,
I am running this command verbatim:

docker run -d -p 8083:8083 -v recorder_store:/store -e OTR_HOST=mqtt_broker owntracks/recorder

But all it does is print a long hex string and nothing starts.
Checking with "docker ps" doesn't list anything.
Any advice?

**Comment by jpmens** [comment]
can you remove the image and start over? (docker images; docker rmi)

**Comment by olegmeister** [comment]
Thanks. I didn't understand I needed to install an mqtt service first.
I installed and was able to test it from two terminal windows  but the image still cannot connect to it, fails with "connecting to MQTT on<host>:<port> as clientID ot-recorder-<containerid> without TLS"
Unable to connect (15) [Lookeup error.]: unknown reason.

**Comment by wisehackermonkey** [comment]
![image](https://user-images.githubusercontent.com/29699356/148304944-3ee9c458-5782-4bdd-8fea-0283fce3d67c.png)

**Comment by jpmens** [comment]
@olegmeister have you meanwhile succeeded?

**Comment by olegmeister** [comment]
No, I have not :( Thanks for reaching out. I'll try it again this weekend.

**Comment by jpmens** [comment]
Closing as stale. Feel free to open if necessary.
