### ISSUE TITLE
Payload encryption configuration

### ISSUE THREAD

**Issue by whiteneon** [owntracks/docker-recorder#44]
I am pretty new to docker in general so please excuse my ignorance, but is it possible to use the ocat program to add user:key combinations to be loaded from the config volume?  When monitoring logs I get error: 'No decryption key for XXX' when a user publishes encrypted location data

From owntracks/recorder github page:
`echo "jjolie-iphone s3cr1t" | ocat --load=keys`

Or am I way off base here?

**Comment by jpmens** [comment]
That ought to be possible with an invocation of docker to obtain _ocat_ and by specifying the volume accordingly.

**Comment by whiteneon** [comment]
Thanks for the assistance. Lack of working knowledge with docker seems to be the culprit. I did get it working using your assistance.
