### ISSUE TITLE
Build error in hooks.c on RPi 3B+

### ISSUE THREAD

**Issue by grimpeur78** [owntracks/docker-recorder#46]
Hi guys, I want to update my Recorder install from 0.8.6 to 0.8.7 on my RPi 3B+. I had installed 0.8.6 by manually building the docker image on the Pi from this git without problems.

However, now that I want to build 0.8.7 I am running into an error message that prevents the build process from completing. I've attached the log below.

Any ideas as to what's going wrong? Any help is appreciated!

Thanks for keeping this awesome project up!

[ot-recorder.log](https://github.com/owntracks/docker-recorder/files/7466844/ot-recorder.log)

**Comment by jpmens** [comment]
From the provided logfile:

```
mhooks.c: In function 'otr_strftime':
mhooks.c:532:20: error: passing argument 1 of 'gmtime' from incompatible pointer type [-Werror=incompatible-pointer-types]
  532 |   if ((tm = gmtime(&secs)) != NULL) {
      |                    ^~~~~
      |                    |
      |                    long int *
In file included from hooks.c:24:
/usr/include/time.h:57:20: note: expected 'const time_t *' {aka 'const long long int *'} but argument is of type 'long int *'
   57 | struct tm *gmtime (const time_t *);
      |                    ^~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [<builtin>: hooks.o] Error 1
```

**Comment by grimpeur78** [comment]
Unfortunately, the error persists even after having upgraded from Raspbian Buster to Bullseye :/

**Comment by grimpeur78** [comment]
Perfect, it builds flawlessly! Thanks alot for your work!
