### ISSUE TITLE
Noob Guide installation

### ISSUE THREAD

**Issue by 0xspade** [owntracks/docker-recorder#47]
The installation process of this one is quite a bit confusing for a beginner just like me. Can you suggest or create a noob-friendly installation on this one? like installing an MQTT_broker first, or does the mqtt_broker already installed if I pulled the docker image of owntracks recorder. I reviewed the repo of recorder, and frontend but I can't manage to run it.

**Comment by joaofar** [comment]
Yes, second this.

I usually end up managing to get a bit more techy things working but this one is just refusing to start. I managed to get the frontend working pretty easily but the recorder refuses to work and I have no clue why.

It would be nice to have a step by step guide for typical scenarios with concrete examples which I couldn't find anywhere on the web.

**Comment by stlinkgangs** [comment]
I have the same issue

**Comment by jpmens** [comment]
Understood, and we've now done this, however sans docker. We hope our [quicksetup](https://owntracks.org/booklet/guide/quicksetup/) will very greatly assist people who don't spend their whole day in front of a command line. :-) 


Feedback is appreciated at the [quicksetup repo](https://github.com/owntracks/quicksetup/issues).
