### ISSUE TITLE
Environment variable OTR_TOPICS has no effect

### ISSUE THREAD

**Issue by saesh** [owntracks/docker-recorder#49]
When passing the environment variable `OTR_TOPICS` to the docker container it is not overriding what is written in the `recorder.conf` file.

```
$ docker inspect owntracks-recorder
...
"Config": {
            "Env": [
                ...
                "OTR_TOPICS=owntracks/some-user/#",
            ],
}
```

When looking at the logs of the container it subscribes to the topic defined in the default `recorder.conf`:

```
$ docker logs owntracks-recorder
ot-recorder[11]: Subscribing to owntracks/# (qos=2)
```

And the `recorder.conf`:

```
$ cat owntracks-recorder-volume/config/recorder.conf
OTR_TOPICS = "owntracks/#"
```

**Comment by jpmens** [comment]
That is correct: `OTR_TOPICS` is not retrieved from the environment and is documented thusly in the [Recorder README](https://github.com/owntracks/recorder/blob/master/README.md), in the table of `OTR_` settings.

**Comment by jpmens** [comment]
I have opened an an enhancement issue at our Recorder repository, so I am closing here. Thanks for reporting.

**Comment by saesh** [comment]
Thank you @jpmens!
