### ISSUE TITLE
Latest pull request is forcing TLS.

### ISSUE THREAD

**Issue by grheard** [owntracks/docker-recorder#53]
Pull request #52 is forcing TLS with an internally defined OTR_CAFILE environment variable.

My internal LAN setup does not use TLS to the broker on the same machine, but when I updated to the latest docker TLS is being forced on by an environment variable defined in the Dockerfile.

**Comment by jpmens** [comment]
I'm sorry that happened, it should not have. Mea culpa: I didn't pay enough attention. I will revert (comment out those bits and rebuild the image).

**Comment by jpmens** [comment]
Could you please see if owntracks/recorder   `0.8.8-15` works for you?

**Comment by jpmens** [comment]
`0.8.8-17`

**Comment by grheard** [comment]
Confirmed working again, Thanks!
