### ISSUE TITLE
Installed as per instructions - not accessible on port 8083

### ISSUE THREAD

**Issue by grumpazoid** [owntracks/docker-recorder#58]
After starting the container, the web interface is not accessible on LANIP:8083 via browser
The machine docker runs on has no GUI/Browser

My docker run command is :
docker run -itd \
-p 8083:8083 \
--name=owntracks  \
--restart=unless-stopped \
--net=nginx-pm_default \
-e OTR_HOST=mqtt \
-e OTR_PORT=1883 \
-e OTR_USER=user \
-e OTR_PASS=pass \
-v recorder_store:/store \
-v /home/user/owntracks/config:/config \
owntracks/recorder

Adding the following lines does not help
-e OTR_HTTPHOST=0.0.0.0 \
-e OTR_HTTPPORT=8083 \

I can see by looking in the logs that the container has connected to my broker and has started.

I think I have a similarr issue to https://github.com/owntracks/docker-recorder/issues/55 but I do not understand how to fix.

All my other containers are accessible via the LAN on the mapped port given in the docker run command.

**Comment by jpmens** [comment]
`OTR_HTTPOST` is not taken from the environment, yet. So please create a `recorder.conf` and configure it therein.

**Comment by grumpazoid** [comment]
@jpmens Thanks for that info. It worked.
Just to confirm fo others to find, I had add OTR_HTTPHOST = "0.0.0.0" in the recorder.conf file.
Would be good if this was made available on the instructions page.

**Comment by jpmens** [comment]
This has now **finally** been fixed; all settings are taken first from compiled-in defaults, then from the configuration file, then from the environment, and finally from command-line options if specified.

**Comment by Fratt** [comment]
Thanks a lot!
Any clue when this will be available on the `latest` tag of Docker Hub?
I'm configuring it fully with env variables.

**Comment by jpmens** [comment]
When we next cut a release of the Recorder, I will rebuild the container images. This will be at least a week now, as we're in the process of testing a whole lot of things.

**Comment by Fratt** [comment]
Thanks a lot!

**Comment by jpmens** [comment]
@Fratt released a few minutes ago.
