### ISSUE TITLE
Best practice: How to archive data older than 30 days?

### ISSUE THREAD

**Issue by ituri** [owntracks/docker-recorder#62]
Hi everyone,

I've successfully set up owntracks and I like the project quite a lot. The only thing I'm wondering: Is there any way to store data for longer than just the default 30 days? If no, how do others automate archiving their location data?

**Comment by jpmens** [comment]
With OwnTracks Recorder (which you appear to be using if you raise the issue in this repository) there is no default and certainly none of 30 days; data is persisted until you delete it from the data store (documentation calls this STORAGE). If you wish to archive data outside of the Recorder, you can use its `ocat` utility to extract it in different formats.

**Comment by ituri** [comment]
I'm sorry, I must have had some filter turned on. Checking just now, you're right: There is all the data, starting from the beginning. Thanks for clearing that up and thanks for this wonderful piece of software. 😊
