### ISSUE TITLE
Alternative registry

### ISSUE THREAD

**Issue by jpmens** [owntracks/docker-recorder#66]
I think we're going to need an alternative registry according to my understanding of the [Docker announcement](https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/)

![rabbit-10208](https://user-images.githubusercontent.com/60706/226098870-91a4d05f-ab5d-4fc5-b2a0-d2efe19fc25c.png)

### This is our docker page

![rabbit-10207](https://user-images.githubusercontent.com/60706/226098882-84fd8353-f4af-401e-8a6e-973d68ff9454.png)

**Comment by jpmens** [comment]
> Thank you for completing the Docker Open Source application. We do our best to process applications within 30 days. We’re currently experiencing a high volume of requests and may take longer than normal to respond.

**Comment by aniston** [comment]
Docker has reversed it's "Sunsetting" decision at the end of March https://www.docker.com/blog/no-longer-sunsetting-the-free-team-plan 

- so-far-so-good, but an alternative is good to have, before ..the Sun does set ;)

**Comment by jpmens** [comment]
Closing this as stale. I agree with @aniston, but we'll cross that bridge when we get there. :-)
