### ISSUE TITLE
docker linux/arm64 build

### ISSUE THREAD

**Issue by aniston** [owntracks/docker-recorder#68]
The docker builds in linux/amd64 worked for the Frontend and Recorder and thanks for that.

While testing the ARM ARCH only the owntracks/frontend runs but cannot run the owntracks/recorder container as it does not have a linux/arm64 OS/ARCH with the container log error `exec /usr/sbin/entrypoint.sh: exec format error`

- any chance of an official linux/arm64 arch for the owntracks/recorder ?

**Comment by jpmens** [comment]
That sounds as though the hash-bang line isn't being recognized. `entrypoint.sh` contains

```
#!/bin/sh
```

in its first line. 

Could you please show the output of these two commands?

```
$ ls -l /bin/sh
$ ls -lL /bin/sh
```

from inside the container?

**Comment by aniston** [comment]
@jpmens thanks for looking into the issue.

sadly i cannot run anything inside the container as it is not running or better still constantly restarting. 
`Error response from daemon: Container 71d430f4aa3adc8145701f760b8089940295f8184b8e642ab64c51b20e1c9976 is restarting, wait until the container is running`

I used the following command on the container:
`docker exec -it otrecorder "ls -l /bin/sh"`
- is there another way to run those commands on a container that is not starting or restating ?

**Comment by jpmens** [comment]
Does this work?

```
docker run -it --entrypoint=/bin/sh otrecorder
```

Though if it does, then `/bin/sh` is there and it's executable so that will invalidate my earlier assumption that the shell is broken.

**Comment by jpmens** [comment]
If you do get a shell, then please show the output of

```
cat /usr/sbin/entrypoint.sh
env
```

**Comment by aniston** [comment]
> you are running an Arm image on an amd64 host or vice versa.

yup exactly, that's the reason for the request for an arm64 build.

**Comment by aniston** [comment]
> ```
> docker run -it --entrypoint=/bin/sh otrecorder
> ```

this does not work as per the same bild issue , ie: ARCH mismatch from pulled image incompability.
I paste the resulting error message from docker.
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /bin/sh: exec format error
```

**Comment by aniston** [comment]
@jpmens I am using a Hetzner VPS with ARCH=ARM64 ARM Ampere CPU and sucessfully built the Docker image on the docker host using the Dockerfile on github with

`docker buildx build -t otrecorder:arm64 github.com/owntracks/docker-recorder`

this image runs correctly in the container, so if needed I can carry out some test here.
- the host OS is `linux aarch64 Debian GNU/Linux 11 (bullseye)` with Kernel Version `5.10.0-21-arm64`
HTH.

**Comment by jpmens** [comment]
Apologies for this taking so long, but if I haven't messed this up, we now have Recorder images for ARM:

![rabbit-10504](https://github.com/owntracks/docker-recorder/assets/60706/0463c2f4-a66e-4773-bdce-5d9c85989c71)

We'd appreciate your testing!

**Comment by jpmens** [comment]
We have reports that these are working. Closing as completed.

**Comment by aniston** [comment]
> Apologies for this taking so long, but if I haven't messed this up, we now have Recorder images for ARM:
> 
> ![rabbit-10504](https://private-user-images.githubusercontent.com/60706/277927020-0463c2f4-a66e-4773-bdce-5d9c85989c71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MTMwMDgsIm5iZiI6MTcxMDYxMjcwOCwicGF0aCI6Ii82MDcwNi8yNzc5MjcwMjAtMDQ2M2MyZjQtYTY2ZS00NzczLWJkY2UtNWQ5Yzg1OTg5YzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDE4MTE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzNzg3NTZjMzM1MjQ3YTZlMDMwMGI2OGE2YjNiMzI0YmFhNTQ1ODJiZGZjY2ExYmRkNDk3MzJjZDBiZjU3NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K1MnKj6t-JToB5b1NEEOzoBFWWJBqjlXPfE6Z0GJO3s)
> 
> We'd appreciate your testing!

@jpmens , seen this message only today and tried out your official docker-recorder build, yes it works fine, I had till today resorted to using my own docker image at cavia/otrecorder for arm64 hence i forget to check this ticket. I confirm that on my ARM VPS at Hetzner it workes correctly, Thanks for the ARM64 image.
