### ISSUE TITLE
User and Device configuration

### ISSUE THREAD

**Issue by thunt-career** [owntracks/docker-recorder#80]
I am trying to set up the configuration.yml for users. I couldn't figure out through the recorder, quick setup and booklet. I opened shell in the docker container and `ocat --list` gave me an error unable to open file. I did not specify a user when I attached.

I think ideally the configuration.yml could be passed in through a volume mount then run the bootstrap.sh with the entry point.sh. I did not see the bootstrap or anything in the container directories. I assume all of that is handled by the docker image builder.

**Comment by jpmens** [comment]
>I am trying to set up the configuration.yml for users.

configuration.yml is a file which belongs to quicksetup. Please see our documentation on what that is at https://owntracks.org/booklet/guide/quicksetup/ and the repository at https://github.com/owntracks/quicksetup .

The latter has its own Issues tracker, in case you require assistance or wish to report a bug.

Note that quicksetup does *not* use docker; you'll need a VPS or a small computer to get started, and it's our recommended way of getting OwnTracks running.

**Comment by thunt-career** [comment]
@jpmens correct and I understand that. For the docker setup, what is the intention to handle users and devices? Is that not a necessary part of the configuration? I'm a bit surprised the yml with the quick setup is the only way to enter this info.

**Comment by jpmens** [comment]
users and devices don't need to be configured for MQTT. Other other available protocols is too complex in Docker as we currently have no provision for updating the database while ot-recorder is running in the container.
