### ISSUE TITLE
Looking for an Owntrack Developer with interest to build an innovative solution 

### ISSUE THREAD

**Issue by Scharla2407** [owntracks/docker-recorder#81]
Hi
I just read about OwnTracks in Germany‘s leading computer magazine (ct‘) and think it could be a great basis for an innovative application I am having in mind since a few years and have not seen being covered by any other product or service, yet. Would love to exchange thoughts with someone who is deep enough into OwnTrack‘s code to judge whether it really is a good basis. 
As a little background infomation: I am a partner in a strategy consulting firm and know a thing or two about business plans… and could either invest myself or get funding IF we find the idea being realistically doable. If you are interested ,Pls email me at owntracks@scharlach.com

**Comment by Scharla2407** [comment]
Hi Jan-Piet,

My apologies if my post has been seen as spam. Was clearly not my intention. Being new to GitHub and not a programmer myself, can you please help me and give guidance how to reach out to suitable people properly?

Thanks and cheers,

Armin Scharlach
***@***.***
CH: Seestrasse 212, 8806 Bäch SZ, +41-78-2246111
DE: Havelchaussee 155, 14055 Berlin, +49-175-1011001
ES: Camino Jose Pons La Jurona 63, 38760 Los Llanos, +34-613-875-183

Am 11.07.2024 um 18:48 schrieb Jan-Piet Mens ***@***.***>:

﻿

Closing as spam

**Comment by jpmens** [comment]
The core OwnTracks team is at ***@***.***

**Comment by Scharla2407** [comment]
Good morning , Jan-Piet,
I just recognised that GitHub is x-ing out email addresses. Let’s see with my own address as an example whether it works substituting that at-Symbol : arain AT scharlach DOT com.
If that worked I would be thankful if you can share the address of the core team in that format as well.
Thanks and have a nice weekend,

Armin Scharlach

Am 12.07.2024 um 00:30 schrieb Jan-Piet Mens ***@***.***>:

﻿

The core OwnTracks team is at ***@***.***

**Comment by jpmens** [comment]
My mistake; I responded by email. Address corrected.
