### ISSUE TITLE
No data being displayed in browser

### ISSUE THREAD

**Issue by whalecoiner** [owntracks/docker-recorder#83]
Hey all,

I'm trying to get owntracks-recorder going via Docker. The web interface works, but I'm not getting any tracking data showing up.

```
+ version 0.9.8 starting with STORAGEDIR=/store
+ connecting to MQTT on mqtt.<REDACTED>:1883 as clientID ot-recorder-8bced8aebe07-6 without TLS
+ HTTP listener started on 0.0.0.0:8083, without browser-apikey
+ HTTP prefix is unset
+ Using storage at /store with precision 7
+ TZDATADB is at /config/timezone16.bin: ENOENT
+ Subscribing to owntracks/# (qos=2)
+ http: GET /
+ http: GET /api/0/last
/store/last: No such file or directory
+ no decryption key for <REDACTED>-iphone in owntracks/<REDACTED>/iphone/status
```

As you can see from the above, my phone is sending data to the broker, and the recorder is connecting to it in turn. 

Is this because I have no TLS encryption enabled? I didn't feel that I had to, as I'm running this via a private wireguard tunnel (Tailscale) from phone to broker.

Any help is gratefully received!

EDIT: config for completeness.

```
OTR_HOST="mqtt.<REDACTED>"
OTR_TOPICS="owntracks/#"
```

**Comment by jpmens** [comment]
```
+ no decryption key for <REDACTED>-iphone in owntracks/<REDACTED>/iphone/status
```

This indicates that you've probably configured a `secret` encryption key on your mobile device, but the server (i.e. Recorder) doesn't have a key with which to decrypt the data.

Please verify whether you see data in your `<store>`: you should have a `rec/<REDACTED>/iphone/2024-08.rec` file there in which case data is actually being received.

Then, please remove the _secret_ from the device (backspace it away), and try publishing manually again.

**Comment by jpmens** [comment]
I ought to add that _publishing manually_ means hitting the up-arrow-share button on the main display. ;) 

![rabbit-11201](https://github.com/user-attachments/assets/43bd1a2a-d2c2-4585-939b-55c63edd5459)

**Comment by whalecoiner** [comment]
Thank you! I think the decryption issue was a distraction. It turned out that I had been hitting "Publish" in the settings, rather than the one screenshotted.

Thanks for the time and the help - all working now. :)

**Comment by jpmens** [comment]
> hitting "Publish" in the settings

yes, we had that recently with someone, and I would have still being debugging their issue if @ckrey hadn't come up with that happening, hence my screenshot.

The Publish in settings sends a Status message ([example](https://github.com/owntracks/recorder/issues/482#issuecomment-2258603139)), and I'm going to suggest we rename that button. :-)

Glad you got it sorted!
