### ISSUE TITLE
docker health check

### ISSUE THREAD

**Issue by centralhardware** [owntracks/docker-recorder#84]
As far as I can see, there was a health check before, but then for some reason it was deleted

**Comment by jpmens** [comment]
… and your question/issue is …?

**Comment by centralhardware** [comment]
It would be convenient if owntrack-recorder had a health check like most Docker Images

**Comment by jpmens** [comment]
As you’ve already determined, it was decided to remove it. I don’t remember the details but am sure they’re in an issue here somewhere
